// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3gB4qBlgYW7_nLd8JZijyha0xXekGuaE',
    appId: '1:518875377655:web:460e04cac1603f2545c8f2',
    messagingSenderId: '518875377655',
    projectId: 'geocharge-f6714',
    authDomain: 'geocharge-f6714.firebaseapp.com',
    storageBucket: 'geocharge-f6714.firebasestorage.app',
    measurementId: 'G-3DK8B61WL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbragA74rNfucFNiCSeLbTvdLHJKb6unc',
    appId: '1:518875377655:android:384163f58a2e49fe45c8f2',
    messagingSenderId: '518875377655',
    projectId: 'geocharge-f6714',
    storageBucket: 'geocharge-f6714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZhLQqpFwgPs6G9bou01DHfJKc5tJ3_LQ',
    appId: '1:518875377655:ios:5854526050fe05e945c8f2',
    messagingSenderId: '518875377655',
    projectId: 'geocharge-f6714',
    storageBucket: 'geocharge-f6714.firebasestorage.app',
    iosClientId: '518875377655-n322qmdoqnp81g0gno2kvjrllu3o1utl.apps.googleusercontent.com',
    iosBundleId: 'com.example.evChargerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZhLQqpFwgPs6G9bou01DHfJKc5tJ3_LQ',
    appId: '1:518875377655:ios:5854526050fe05e945c8f2',
    messagingSenderId: '518875377655',
    projectId: 'geocharge-f6714',
    storageBucket: 'geocharge-f6714.firebasestorage.app',
    iosClientId: '518875377655-n322qmdoqnp81g0gno2kvjrllu3o1utl.apps.googleusercontent.com',
    iosBundleId: 'com.example.evChargerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3gB4qBlgYW7_nLd8JZijyha0xXekGuaE',
    appId: '1:518875377655:web:6b55259ae644a3b245c8f2',
    messagingSenderId: '518875377655',
    projectId: 'geocharge-f6714',
    authDomain: 'geocharge-f6714.firebaseapp.com',
    storageBucket: 'geocharge-f6714.firebasestorage.app',
    measurementId: 'G-T27VZQ10Q6',
  );
}
