#!/usr/bin/env node
// Schedules the GeoCharge app poster campaign: nine posters, one a week, on
// Thursday evening, on the Facebook page and on Instagram.
//
//   node tools/poster-queue.mjs              # dry run, writes marketing/posters/queue.md
//   node tools/poster-queue.mjs --publish    # actually schedules on Facebook
//   node tools/poster-queue.mjs --export     # writes functions/poster-content.json for Instagram
//   node tools/poster-queue.mjs --doc        # rewrites marketing/posters/captions.md
//   node tools/poster-queue.mjs --list       # what is already in the Facebook queue
//   node tools/poster-queue.mjs --cancel <id>
//
// The captions live in this file and nowhere else. Facebook reads them from
// here at scheduling time, Instagram reads them from the exported JSON that is
// deployed with the function, and the human readable copy deck is generated by
// --doc. Editing captions.md by hand therefore changes nothing.
//
// Facebook and Instagram are scheduled by different machinery for the reason
// spelled out in functions/instagram.js: the Pages API takes a future publish
// time, the Instagram Graph API does not.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const STATE = path.join(ROOT, 'tools', 'poster-state.json');
const QUEUE_MD = path.join(ROOT, 'marketing', 'posters', 'queue.md');
const CAPTIONS_MD = path.join(ROOT, 'marketing', 'posters', 'captions.md');
const EXPORT = path.join(ROOT, 'functions', 'poster-content.json');
const ORIGIN = 'https://geocharge.ge';
const API = process.env.FB_API_VERSION || 'v26.0';

// Asia/Tbilisi is UTC+4 all year, no DST. One slot: Thursday evening, which is
// clear of the blog queue (Tuesday 19:00 and Saturday 12:00).
const TZ = 4;
const SLOT = { dow: 4, h: 19, m: 0 };

// Facebook refuses a scheduled time much past a month out. Measured against the
// live page on 2026-08-19: 27 days ahead accepted, 31 refused. Nine weekly
// slots span 57 days, so a first run queues what fits and a later run tops the
// rest up. Instagram has no such ceiling because its publisher is a cron.
const HORIZON_DAYS = 29;

const LINK = `${ORIGIN}/get/`;

const IG_CLOSE = 'ბმული ბიოშია 🔗';

// The campaign, in the order it goes out. `fb` carries the clickable link,
// `ig` closes on the bio line and the tags, because Instagram does not make a
// caption link tappable.
//
// Two rules hold across every caption and are worth stating once: Turkey is not
// mentioned in this campaign, and neither is premium. The app is free and no
// feature is behind a paywall; premium only switches the ads off, so wording
// like "paid version" would read as a limit that does not exist.
const POSTERS = [
  {
    slug: '01-ufaso',
    title: 'უფასო',
    fb: `ელექტრომობილი იმიტომ იყიდე, რომ ნაკლები დაგეხარჯა.

GeoCharge ამავე ლოგიკას მიჰყვება. 800-ზე მეტი დამტენი სადგური, 12 ქსელი ერთ რუკაზე, ცოცხალი სტატუსი და მარშრუტის დაგეგმვა. ყველაფერი ეს 0 ლარად.

არც აბონენტი, არც სარეგისტრაციო საფასური. აპლიკაციის ყველა ფუნქცია ღიაა ყველა მძღოლისთვის.

ჩამოტვირთე ახლავე 👉 ${LINK}`,
    ig: `რამდენი გიღირს დამტენის პოვნა? 0 ლარი. ⚡

800+ სადგური, 12 ქსელი, ცოცხალი სტატუსი და მარშრუტი დატენვის გაჩერებებით. ყველა ფუნქცია ღიაა.

გადმოწერე ახლავე, ${IG_CLOSE}`,
    tags: ['#GeoCharge', '#ელექტრომობილი', '#დამტენი', '#EV', '#EVCharging', '#საქართველო', '#ელექტრომობილისაქართველოში'],
  },
  {
    slug: '02-erti-ruka',
    title: 'ერთი რუკა',
    fb: `საქართველოში დამტენი ქსელები ერთმანეთისგან დამოუკიდებლად მუშაობს და თითოეულს თავისი აპლიკაცია აქვს. სანამ თავისუფალ სადგურს იპოვი, ტელეფონში რიგრიგობით ხსნი ხოლმე ყველას.

GeoCharge სწორედ ამ ნაწილს ხურავს. ერთ რუკაზე ხედავ ყველა ქსელის სადგურს: სად არის, რომელი ოპერატორია, რა კონექტორი აქვს, რა ღირს და თავისუფალია თუ არა.

დამტენს ჩვენთან პოულობ, დატენვას კი იმ ქსელის აპლიკაციით იწყებ, რომელსაც სადგური ეკუთვნის.

ჩამოტვირთე ახლავე 👉 ${LINK}`,
    ig: `ერთი რუკა თორმეტი ქსელისთვის 🗺️

mart EV, E-Space, EcoCars, Da-Tene, Tegeta, Charger Plus და დანარჩენები. ყველა ერთად, ერთ ეკრანზე.

სად არის, რა ღირს და თავისუფალია თუ არა, ერთი შეხედვით ხედავ.

${IG_CLOSE}`,
    tags: ['#GeoCharge', '#ელექტრომობილი', '#დამტენი', '#EV', '#EVCharging', '#საქართველო', '#მართევ', '#ეკოკარსი'],
  },
  {
    slug: '03-shematyobine',
    title: 'შემატყობინე',
    fb: `მიდიხარ დამტენთან და დაკავებულია. მერე რა? დგახარ და ელოდები, თუ სხვას ეძებ?

GeoCharge-ს მესამე გზა აქვს. დაკავებულ დამტენზე შეტყობინებას რთავ და ტელეფონი თავად გაცნობებს იმ წამსვე, როგორც კი პორტი გათავისუფლდება. ერთდროულად ოთხ სადგურამდე შეგიძლია ასე დააკვირდე.

ამ დროს კი მშვიდად სვამ ყავას, ნაცვლად იმისა, რომ მანქანაში იჯდე და თვალი ეჭირო.

ჩამოტვირთე ახლავე 👉 ${LINK}`,
    ig: `დაკავებულია? ნუ დგახარ და ნუ ელოდები. 🔔

ჩართე შეტყობინება და ტელეფონი თავად გეტყვის, როცა დამტენი გათავისუფლდება. ერთდროულად 4 სადგურამდე.

ასეთი ფუნქცია სხვაგან არ გაქვს.

${IG_CLOSE}`,
    tags: ['#GeoCharge', '#ელექტრომობილი', '#დამტენი', '#EV', '#EVCharging', '#საქართველო'],
  },
  {
    slug: '04-cocxali-statusi',
    title: 'ცოცხალი სტატუსი',
    fb: `15 კილომეტრი გაიარე დამტენამდე და ადგილზე აღმოჩნდა, რომ ის ან დაკავებულია, ან საერთოდ არ მუშაობს. ყველაზე გამაღიზიანებელი რამ ელექტრომობილში ეს არის.

GeoCharge ყველა პორტის სტატუსს რეალურ დროში აახლებს. სანამ სახლიდან გახვალ, უკვე იცი, თავისუფალია სადგური, დაკავებულია, თუ მწყობრიდან არის გამოსული.

ერთი შეხედვა ეკრანზე და გზა ტყუილად აღარ იკარგება.

ჩამოტვირთე ახლავე 👉 ${LINK}`,
    ig: `გასვლამდე იცოდე, თავისუფალია თუ არა 🟢🟡🔴

ცოცხალი სტატუსი რეალურ დროში: თავისუფალი, დაკავებული, მწყობრიდან გამოსული.

15 კილომეტრი ტყუილად აღარ იარო.

${IG_CLOSE}`,
    tags: ['#GeoCharge', '#ელექტრომობილი', '#დამტენი', '#EV', '#EVCharging', '#საქართველო', '#ცოცხალისტატუსი'],
  },
  {
    slug: '05-marshruti',
    title: 'მარშრუტი',
    fb: `თბილისიდან ბათუმამდე ელექტრომობილით ჩასვლა სულაც არ არის რთული. რთული მაშინ ხდება, როცა გზაში ფიქრობ, სად და როდის უნდა გაჩერდე.

მიუთითე საიდან და სად მიდიხარ, GeoCharge თავად შეარჩევს დატენვის გაჩერებებს გზაზე, გეტყვის რამდენი პროცენტით ჩახვალ თითოეულთან და მონიშნავს იმ დამტენებს, რომლებიც გზის სწორ მხარესაა, რომ შემობრუნება არ დაგჭირდეს.

მერე კი ერთი ღილაკით გადადიხარ Google Maps-ში და მიდიხარ.

ჩამოტვირთე ახლავე 👉 ${LINK}`,
    ig: `თბილისი ბათუმი ერთი გაჩერებით 🚗⚡

აპლიკაცია თავად შეარჩევს, სად დაიტენო, გეტყვის რამდენი პროცენტით ჩახვალ და მონიშნავს დამტენებს გზის სწორ მხარეს.

შემდეგ პირდაპირ Google Maps-ში აგრძელებ.

${IG_CLOSE}`,
    tags: ['#GeoCharge', '#ელექტრომობილი', '#მარშრუტი', '#EV', '#EVRoadTrip', '#საქართველო', '#ბათუმი'],
  },
  {
    slug: '06-konektori',
    title: 'კონექტორის ფილტრი',
    fb: `CCS2, Type 2, CHAdeMO თუ GB/T. შენს მანქანას კონკრეტული კონექტორი სჭირდება, რუკაზე კი ოთხივე გიჩანს და თვალით ჩხრეკ, რომელია შენი.

GeoCharge-ში ერთხელ შეავსებ მანქანის პროფილს და რუკა შემდეგ თავად მოირგებს. ხედავ მხოლოდ იმ სადგურებს, სადაც რეალურად დატენავ.

ფილტრი მუშაობს კონექტორზე, სიმძლავრეზე და ოპერატორზეც. გინდა მხოლოდ სწრაფი DC 50 კილოვატიდან ზემოთ? ორი შეხებაა.

ჩამოტვირთე ახლავე 👉 ${LINK}`,
    ig: `შენს მანქანას კონკრეტული კონექტორი სჭირდება. რატომ უნდა ეძებო ის დანარჩენ სამს შორის? 🔌

ერთხელ შეავსებ მანქანის პროფილს და რუკა თავად მოირგებს. კონექტორი, სიმძლავრე, ოპერატორი.

სწრაფი DC 50 კვტ-დან ზემოთ? ორი შეხება.

${IG_CLOSE}`,
    tags: ['#GeoCharge', '#ელექტრომობილი', '#CCS2', '#Type2', '#CHAdeMO', '#EV', '#EVCharging', '#საქართველო'],
  },
  {
    slug: '07-tarifebi',
    title: 'ტარიფები',
    fb: `ერთი და იგივე დატენვა სხვადასხვა ქსელში თითქმის ორმაგად განსხვავებული ფასი შეიძლება იყოს. ყველაზე იაფი სწრაფი დამტენი 0.55 ლარს იღებს კილოვატსაათზე, ყველაზე ძვირი კი 1 ლარს.

60 კილოვატსაათიან ბატარეაზე ეს განსხვავება 27 ლარია. ერთი დატენვისთვის.

GeoCharge-ში ფასი ყველა სადგურის ბარათზე წერია და პროვაიდერებისგან ავტომატურად ახლდება, ასე რომ სანამ მიხვალ, უკვე იცი რა დაგიჯდება.

ჩამოტვირთე ახლავე 👉 ${LINK}`,
    ig: `0.55 ლარი თუ 1.00 ლარი კილოვატსაათზე? 💸

სხვაობა ერთ დატენვაზე 27 ლარამდე ადის.

GeoCharge-ში ფასი ყველა სადგურის ბარათზე წერია და ავტომატურად ახლდება. მისვლამდე იცი, რა დაგიჯდება.

${IG_CLOSE}`,
    tags: ['#GeoCharge', '#ელექტრომობილი', '#ტარიფები', '#დამტენი', '#EV', '#EVCharging', '#საქართველო'],
  },
  {
    slug: '08-dafarva',
    title: 'დაფარვა',
    fb: `800-ზე მეტი საჯარო დამტენი სადგური საქართველოსა და რეგიონში, 12 ქსელიდან, ერთ რუკაზე.

ქალაქის ცენტრებიდან საქალაქთაშორისო მაგისტრალებამდე. სადაც არ უნდა იმგზავრო, უახლოესი დატენვის ადგილი ჯიბეშია.

რუკა კი თავისით იზრდება. ახალი სადგური ავტომატურად ჩნდება მაშინვე, როგორც კი პროვაიდერი მას აამუშავებს, აპლიკაციის განახლების ლოდინი არ გჭირდება.

ჩამოტვირთე ახლავე 👉 ${LINK}`,
    ig: `800+ სადგური. 12 ქსელი. 1 რუკა. 🇬🇪

ქალაქის ცენტრიდან მაგისტრალამდე, უახლოესი დამტენი ყოველთვის ჯიბეშია.

ახალი სადგური რუკაზე თავისით ჩნდება, განახლების ლოდინი არ გჭირდება.

${IG_CLOSE}`,
    tags: ['#GeoCharge', '#ელექტრომობილი', '#დამტენი', '#EV', '#EVCharging', '#საქართველო', '#თბილისი', '#ბათუმი', '#ქუთაისი'],
  },
  {
    slug: '09-ucxo-qalaqshi',
    title: 'უცხო ქალაქში',
    fb: `საკუთარ უბანში ყველა დამტენი ზეპირად იცი. ქუთაისში, თელავში ან გუდაურში კი უკვე აღარ, და სწორედ იქ გიჩვენებს ბატარეა 9 პროცენტს.

GeoCharge უახლოეს თავისუფალ დამტენს გაჩვენებს, გეტყვის რამდენი კილომეტრია, რა კონექტორი და რა სიმძლავრე აქვს, და ნავიგაციას იმავე ღილაკიდან გაუშვებს.

უცხო ქალაქში ყველაზე მეტად ეს აპლიკაცია გჭირდება.

ჩამოტვირთე ახლავე 👉 ${LINK}`,
    ig: `უცნობი ქალაქი, ბატარეა 9 პროცენტზე. 🔋

GeoCharge უახლოეს თავისუფალ დამტენს გაჩვენებს, ეტყვის რამდენი კილომეტრია და ნავიგაციასაც იმავე ღილაკიდან გაუშვებს.

ჩამოტვირთე სანამ დაგჭირდება.

${IG_CLOSE}`,
    tags: ['#GeoCharge', '#ელექტრომობილი', '#დამტენი', '#EV', '#EVCharging', '#საქართველო', '#ქუთაისი', '#თელავი', '#გუდაური'],
  },
];

const image = (p) => `${ORIGIN}/assets/social/poster-${p.slug}.png`;
const igCaption = (p) => `${p.ig}\n\n${p.tags.join(' ')}`;

const flag = (n) => process.argv.includes(`--${n}`);
const arg = (n, d) => {
  const i = process.argv.indexOf(`--${n}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : d;
};

const tbilisiUnix = (d, h, m) =>
  Math.floor(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate(), h - TZ, m) / 1000);

const DAYS = ['კვი', 'ორშ', 'სამ', 'ოთხ', 'ხუთ', 'პარ', 'შაბ'];
const stamp = (t) => {
  const d = new Date((t + TZ * 3600) * 1000);
  const hh = String(d.getUTCHours()).padStart(2, '0');
  const mm = String(d.getUTCMinutes()).padStart(2, '0');
  return `${d.toISOString().slice(0, 10)} ${DAYS[d.getUTCDay()]} ${hh}:${mm}`;
};

// Every Thursday slot from `from` onwards, whether or not it fits the Facebook
// horizon. `taken` holds the times earlier runs already used, so a top-up run
// lands after the queue instead of on top of it.
function allSlots(from, count, taken = new Set()) {
  const out = [];
  const day = new Date(Date.UTC(from.getUTCFullYear(), from.getUTCMonth(), from.getUTCDate()));
  const now = Math.floor(Date.now() / 1000);
  while (out.length < count) {
    if (day.getUTCDay() === SLOT.dow) {
      const t = tbilisiUnix(day, SLOT.h, SLOT.m);
      // Facebook refuses anything less than 10 minutes out.
      if (t > now + 900 && !taken.has(t)) out.push(t);
    }
    day.setUTCDate(day.getUTCDate() + 1);
  }
  return out;
}

async function state() {
  if (!existsSync(STATE)) return { posted: [] };
  return JSON.parse(await readFile(STATE, 'utf8'));
}

async function creds() {
  const env = path.join(ROOT, '.env');
  if (existsSync(env)) {
    for (const line of (await readFile(env, 'utf8')).split('\n')) {
      const m = /^\s*([A-Z_]+)\s*=\s*(.*?)\s*$/.exec(line);
      if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  }
  const id = process.env.FB_PAGE_ID;
  const token = process.env.FB_PAGE_TOKEN;
  if (!id || !token) throw new Error('FB_PAGE_ID და FB_PAGE_TOKEN უნდა იყოს .env-ში');
  return { id, token };
}

async function graph(endpoint, params, method = 'GET') {
  const { token } = await creds();
  const body = new URLSearchParams({ ...params, access_token: token });
  const url = `https://graph.facebook.com/${API}/${endpoint}`;
  const res = method === 'GET'
    ? await fetch(`${url}?${body}`)
    : await fetch(url, { method, body });
  const json = await res.json();
  if (json.error) throw new Error(`${json.error.type} ${json.error.code}: ${json.error.message}`);
  return json;
}

// The whole campaign with a time against every poster. Slots already used by an
// earlier run are read back from the state file rather than recomputed, so the
// plan stays stable as the horizon moves and a top-up run cannot shift a poster
// that is already sitting in the Facebook queue.
function planAll(hist) {
  const at = {};
  for (const p of hist.posted) at[p.slug] = p.at;
  const left = POSTERS.filter((p) => !at[p.slug]);
  const times = allSlots(new Date(), left.length, new Set(Object.values(at)));
  left.forEach((p, i) => { at[p.slug] = times[i]; });
  return POSTERS.map((p) => ({ ...p, at: at[p.slug] }));
}

// Neither Cloud Function has a copy of this file, so what they need is exported
// next to them and deployed with them: Instagram takes the caption and the
// image, Facebook additionally takes its own caption, the slot time, and the
// list of posters this laptop has already queued.
async function exportContent() {
  const hist = await state();
  const out = {
    generated: new Date().toISOString().slice(0, 10),
    facebookQueued: hist.posted.map((p) => p.slug),
    posters: planAll(hist).map((p) => ({
      slug: p.slug,
      title: p.title,
      image: image(p),
      at: p.at,
      caption: igCaption(p),
      fb: p.fb,
    })),
  };
  await writeFile(EXPORT, JSON.stringify(out, null, 1), 'utf8');
  console.log(`${out.posters.length} პოსტერი → ${path.relative(ROOT, EXPORT)}`);
  console.log(`Facebook-ზე უკვე დაგეგმილი: ${out.facebookQueued.length}, დანარჩენს ფუნქცია ჩადგამს.`);
}

// The copy deck humans read. Generated so it cannot drift from what is posted.
async function doc() {
  const md = [
    '# სოც ქსელის პოსტერების სერია',
    '',
    'ცხრა პოსტერი Facebook და Instagram feed-ისთვის, 1080×1350.',
    'ვიზუალი გენერირდება `tools/build-posters.mjs`-ით, PNG კი `tools/render-posters.mjs`-ით.',
    '',
    '**ეს ფაილი გენერირებულია.** ქოფები `tools/poster-queue.mjs`-ში ცხოვრობს, აქ ხელით არაფერი იწერება:',
    'ცვლილების შემდეგ გაუშვი `node tools/poster-queue.mjs --doc`.',
    '',
    'გრაფიკი: კვირაში ერთი პოსტი, ხუთშაბათს 19:00, თბილისის დროით, ორივე პლატფორმაზე.',
    `ბმული პოსტში: ${LINK}`,
    '',
    '## წესები ამ სერიისთვის',
    '',
    '- თურქეთი არსად არ ფიგურირებს.',
    '- პრემიუმი არსად არ იხსენიება. აპლიკაცია უფასოა და ყველა ფუნქცია ღიაა, პრემიუმი მხოლოდ',
    '  რეკლამებს თიშავს და ფუნქციებს არ ზღუდავს.',
    '- ტირეები პუნქტუაციად არ გამოიყენება.',
    '',
    ...POSTERS.flatMap((p, i) => [
      '---',
      '',
      `## ${i + 1}. ${p.title} · \`${p.slug}.png\``,
      '',
      '**Facebook**',
      '',
      '```',
      p.fb,
      '```',
      '',
      '**Instagram**',
      '',
      '```',
      igCaption(p),
      '```',
      '',
    ]),
  ].join('\n');
  await writeFile(CAPTIONS_MD, md, 'utf8');
  console.log(`→ ${path.relative(ROOT, CAPTIONS_MD)}`);
}

async function main() {
  if (flag('export')) return exportContent();
  if (flag('doc')) return doc();

  if (flag('list')) {
    const { id } = await creds();
    const r = await graph(`${id}/scheduled_posts`, { fields: 'id,message,scheduled_publish_time', limit: '50' });
    if (!r.data || !r.data.length) return console.log('რიგი ცარიელია.');
    for (const p of r.data) {
      console.log(`${stamp(Number(p.scheduled_publish_time))}  ${p.id}`);
      console.log(`   ${(p.message || '').split('\n')[0].slice(0, 90)}`);
    }
    return;
  }

  if (flag('cancel')) {
    const id = arg('cancel');
    if (!id) throw new Error('--cancel <post-id>');
    await graph(String(id), {}, 'DELETE');
    return console.log(`გაუქმდა: ${id}`);
  }

  const hist = await state();
  const done = new Set(hist.posted.map((p) => p.slug));
  const queue = planAll(hist).filter((p) => !done.has(p.slug));
  if (!queue.length) return console.log('ცხრავე პოსტერი უკვე დაგეგმილია.');

  const now = Math.floor(Date.now() / 1000);
  const limit = now + HORIZON_DAYS * 86400;
  const fits = queue.filter((q) => q.at <= limit);

  const md = [
    '# პოსტერების რიგი',
    '',
    `მომზადდა ${new Date().toISOString().slice(0, 10)}. ${queue.length} პოსტი, ხუთშაბათობით, დრო თბილისის.`,
    '',
    ...queue.map((q) =>
      `- ${stamp(q.at)}  **${q.title}**  \`${q.slug}\`${q.at > limit ? '  (Facebook-ის ფანჯარას სცდება, Instagram მაინც გამოაქვეყნებს)' : ''}`),
    '',
  ].join('\n');
  await mkdir(path.dirname(QUEUE_MD), { recursive: true });
  await writeFile(QUEUE_MD, md, 'utf8');

  for (const q of queue) {
    console.log(`${stamp(q.at)}  ${q.slug}${q.at > limit ? '  [FB: ფანჯრის მიღმა]' : ''}`);
  }
  console.log(`\n→ ${path.relative(ROOT, QUEUE_MD)}`);
  console.log(`Facebook-ზე ახლა ჩაჯდება ${fits.length}/${queue.length}, დანარჩენი მოგვიანებით.`);

  if (!flag('publish')) {
    console.log('\nდაგეგმილი არაფერია, ეს dry run იყო. გასაშვებად: node tools/poster-queue.mjs --publish');
    return;
  }

  const { id } = await creds();
  const posted = [...hist.posted];
  for (const q of fits) {
    // /photos rather than /feed: the poster is the post, and a photo post keeps
    // the full 1080x1350 in the feed instead of a link card crop.
    const r = await graph(`${id}/photos`, {
      url: image(q),
      caption: q.fb,
      published: 'false',
      scheduled_publish_time: String(q.at),
    }, 'POST');
    console.log(`✓ ${stamp(q.at)}  ${q.slug}  ${r.id}`);
    posted.push({ slug: q.slug, at: q.at, id: r.id, post_id: r.post_id || null });
    await writeFile(STATE, JSON.stringify({ posted }, null, 1), 'utf8');
  }
}

main().catch((e) => { console.error(`!! ${e.message}`); process.exit(1); });
